name: GPA Checker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0/20 0-15/1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      # 拉取代码
      - name: Check out code
        uses: actions/checkout@v2

      # 安装 Python 和依赖
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libnss3 libgconf-2-4
          pip3 install -r requirements.txt

      # 运行 GPA 检查器
      - name: Run Python script and get result
        id: run_script
        env:
          STD_ID: ${{ secrets.STD_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOKEN: ${{ secrets.TOKEN }}
          PATH: $HOME/.local/bin:$PATH
        run: |
          python3 main.py > result.txt
          echo "RESULT=$(cat result.txt)" >> $GITHUB_ENV

      # 如果结果有 update，则提交
      - name: Conditional update
        if: contains(env.RESULT, 'update')
        run: |
          git config --global user.email "suny21@m.fudan.edu.cn"
          git config --global user.name "Boreas618"
          git add *
          git commit -m "Automatic update of records"
          git push origin main